<div id="content">
  <div id="preamble">
    <span class="math">\\(\\newcommand{\\sbscript}[2]{#1_{\\text{#2}}}\\)</span>
    <span class="math">\\(\\newcommand{\\spscript}[2]{#1^{\\text{#2}}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbc}{\\mathbb{C}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbn}{\\mathbb{N}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbq}{\\mathbb{Q}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbr}{\\mathbb{R}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbz}{\\mathbb{Z}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbp}{\\mathbb{P}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbps}[1]{\\bbp\\left\\{#1\\right\\}}\\)</span>
    <span class="math">\\(\\newcommand{\\bbpc}[2]{\\bbp\\left\\{#1\\;|\\;#2\\right\\}}\\)</span>
    <span class="math">\\(\\newcommand{\\inflate}[3][,]{#2_{1}#1#2_{2}#1\\ldots#1#2_{#3}}\\)</span>
    <span class="math">\\(\\newcommand{\\inflatec}[3][,]{#2_{1}#1#2_{2}#1\\cdots#1#2_{#3}}\\)</span>
    <span class="math">\\(\\newcommand{\\forward}{(\\Rightarrow)\\;}\\)</span>
    <span class="math">\\(\\newcommand{\\backward}{(\\Leftarrow)\\;}\\)</span>
    <span class="math">\\(\\newcommand{\\norm}[1]{\\|#1\\|}\\)</span>
    <span class="math">\\(\\newcommand{\\dotp}[2]{\\vec{#1}\\cdot\\vec{#2}}\\)</span>
    <span class="math">\\(\\newcommand{\\crossp}[2]{\\vec{#1}\\times\\vec{#2}}\\)</span>
    <span class="math">\\(\\newcommand{\\bcoor}[2][\\beta]{\\left[#2\\right]_{#1}}\\)</span>
    <span class="math">\\(\\newcommand{\\xlimit}[3][]{\\lim\\limits_{#2\\rightarrow #3^{#1}}}\\)</span>
    <span class="math">\\(\\newcommand{\\leibniz}[2][]{\\frac{d#1}{d#2}}\\)</span>
    <span class="math">\\(\\newcommand{\\iprod}[2]{\\langle#1,#2\\rangle}\\)</span>
  </div>
  $if(revision)$
    <h2 class="revision">Revision $revision$</h2>
  $endif$
  <h1 class="pageTitle"><a href="$base$$pageUrl$">$pagetitle$</a></h1>
  $if(messages)$
    $messages()$
  $endif$
  $content$
</div>
